osx_image: xcode7.3
language: objective-c

before_install:
- brew update || brew update
- brew outdated xctool || brew upgrade xctool

script: 
- "xctool clean build -project SnapTimer.xcodeproj -scheme SnapTimer -sdk iphonesimulator"
- "xcodebuild -scheme SnapTimer -project SnapTimer.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test"

after_success:
  - bash <(curl -s https://codecov.io/bash)